version: "3"
services:
  app:
    image: mockoon/cli:latest
    command: mockoon-cli start --data data/env.json --log-transaction --port 3000
    networks:
      - node-red-net
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./project-cs_lokal-api.json
      target: /data/env.json
    ports:
      - "3000:1567"
networks:
  node-red-net:
