version: "3"
services:
  app:
    image: mockoon/cli:latest
    command: mockoon-cli start --data data/env.json --log-transaction --port 3000
    
    restart: unless-stopped
    volumes:
    - type: bind
      source: ./project-cs_lokal-api.json
      target: /env.json
    ports:
      - "3000:3000"
