var api = [
    {
       "local_device_id":0,
       "serial_id":24354325543,
       "product_id":2345534,
       "product_type":3,
       "product_name":"CSM Project",
       "bluetooth_mac":"C0-FD-C2-DF-76-5A",
       "wlan_mac":"C0-FD-C2-DF-76-5B",
       "pos_con":[
          1,
          2,
          3
       ],
       "data_con":[
          
       ],
       "postition":{
          "x":0,
          "y":0,
          "z":0
       },
       "bridging_device":null,
       "device_indication_colour":null
    },
    {
       "local_device_id":1,
       "serial_id":9214708947,
       "product_id":32057493,
       "product_type":32,
       "product_name":"Temperatur Module",
       "bluetooth_mac":"40-FD-C2-DF-76-5A",
       "wlan_mac":"40-FD-C2-DF-76-5B",
       "pos_con":[
          0,
          2,
          3
       ],
       "data_con":[
          0
       ],
       "postition":{
          "x":1.423,
          "y":4.234,
          "z":3.243
       },
       "bridging_device":"CSM Mini",
       "device_indication_colour":"red"
    },
    {
       "local_device_id":2,
       "serial_id":53423426,
       "product_id":32057493,
       "product_type":32,
       "product_name":"Temperatur Module",
       "bluetooth_mac":"A0-FD-C2-DF-76-5A",
       "wlan_mac":"A0-FD-C2-DF-76-5B",
       "pos_con":[
          0,
          1,
          3
       ],
       "data_con":[
          0
       ],
       "postition":{
          "x":5.423,
          "y":4.234,
          "z":3.243
       },
       "bridging_device":null,
       "device_indication_colour":null
    },
    {
       "local_device_id":3,
       "serial_id":645345643,
       "product_id":32057493,
       "product_type":32,
       "product_name":"Temperatur Module",
       "bluetooth_mac":"B0-FD-C2-DF-76-5A",
       "wlan_mac":"B0-FD-C2-DF-76-5B",
       "pos_con":[
          0,
          1,
          2
       ],
       "data_con":[
          0
       ],
       "postition":{
          "x":1.423,
          "y":1.324,
          "z":1.342
       },
       "bridging_device":null,
       "device_indication_colour":null
    },
    {
       "local_device_id":null,
       "serial_id":3456246,
       "product_id":32057493,
       "product_type":32,
       "product_name":"Temperatur Module",
       "bluetooth_mac":"D0-FD-C2-DF-76-5A",
       "wlan_mac":"D0-FD-C2-DF-76-5B",
       "pos_con":[
          0
       ],
       "data_con":[
          null
       ],
       "postition":{
          "x":45.423,
          "y":24.324,
          "z":24.342
       },
       "bridging_device":null,
       "device_indication_colour":null
    },
    {
       "local_device_id":null,
       "serial_id":54323244,
       "product_id":32057493,
       "product_type":32,
       "product_name":"Temperatur Module",
       "bluetooth_mac":"E0-FD-C2-DF-76-5A",
       "wlan_mac":"E0-FD-C2-DF-76-5B",
       "pos_con":[
          0
       ],
       "data_con":[
          null
       ],
       "postition":{
          "x":34.423,
          "y":3.324,
          "z":2.342
       },
       "bridging_device":null,
       "device_indication_colour":null
    }
 ]